=== billhongs/Opentaps-Rest-Api/schema/billing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0"
    xmlns="http://www.opentaps.org/module/ws/rest/domain/billing"
    targetNamespace="http://www.opentaps.org/module/ws/rest/domain/billing">
    <xsd:element name="Invoices" type="invoices"> </xsd:element>

    <xsd:element name="invoice" type="invoice"/>



    <xsd:element name="payments" type="payments"> </xsd:element>
    <xsd:element name="payment" type="payment" nillable="true"/>

    <xsd:complexType name="invoice">
        <xsd:annotation>
            <xsd:appinfo>
                <jaxb:class name="InvoiceBean"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="invoiceId" type="xsd:string" minOccurs="0"/>
            <xsd:element name="invoiceTypeId" type="xsd:string"/>
            <xsd:element name="status" type="xsd:string" minOccurs="0"/>
            <xsd:element name="partyIdFrom" type="xsd:string"/>
            <xsd:element name="partyId" type="xsd:string"/>
            <xsd:element name="currencyUomId" type="xsd:string"/>
            <xsd:element name="invoiceDate" type="xsd:dateTime"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" name="invoiceItems"
                    type="invoiceItem"/>
            </xsd:sequence>
            <xsd:sequence>
                <xsd:element maxOccurs="1" minOccurs="0" ref="payments"/>
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="invoices">
        <xsd:annotation>
            <xsd:appinfo>
                <jaxb:class name="InvoicesBean"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" ref="invoice"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="invoiceItem">
        <xsd:annotation>
            <xsd:appinfo>
                <jaxb:class name="InvoiceItemBean"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="invoiceItemSeqId" type="xsd:string"/>
            <xsd:element name="productId" type="xsd:string"/>
            <xsd:element name="quantity" type="xsd:float"/>
            <xsd:element name="amount" type="xsd:float"/>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="payment">
        <xsd:annotation>
            <xsd:appinfo>
                <jaxb:class name="PaymentBean"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="paymentId" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="payments">
        <xsd:annotation>
            <xsd:appinfo>
                <jaxb:class name="PaymentsBean"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element ref="payment" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== billhongs/Opentaps-Rest-Api/Test/Billing/invoiceCreation.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns="http://www.opentaps.org/module/ws/rest/domain/billing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opentaps.org/module/ws/rest/domain/billing file:/Volumes/Work/Code/Git/Clients/souq/opentaps/rest-api/schema/billing.xsd">

    <invoiceTypeId>SALES_INVOICE</invoiceTypeId>
    <status>INVOICE_READY</status>
    <partyIdFrom>Souq_uae</partyIdFrom>
    <partyId>aabdullah</partyId>
    <currencyUomId>AED</currencyUomId>
    <invoiceDate>2011-10-05T19:15:00</invoiceDate>
    <description>test invoice</description>
    <invoiceItems>
        <invoiceItemSeqId></invoiceItemSeqId>
        <productId></productId>
        <quantity></quantity>
        <amount></amount>
        <description></description>
    </invoiceItems>
    <payment>
        <paymentId></paymentId>
    </payment>
    <payment>
        <paymentId></paymentId>
    </payment>

</invoice>
